#!/bin/bash

# File: hack/generate-authors.sh
# This script generates the AUTHORS file listing all contributors.

# Output the header to the AUTHORS file
echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT." >> AUTHORS
echo "# This file lists all contributors to the repository." >> AUTHORS
echo "# See hack/generate-authors.sh to make modifications." >> AUTHORS

# Use git log to extract contributors and their emails
git log --format='%aN <%aE>' | sort -u >> AUTHORS
